version: '3'
services:
  node-backend:
    build: ./Crypto-backEnd
    container_name: node-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./crypto-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
