apiVersion: apps/v1
kind: Deployment
metadata:
  name: isuru-assignment
  labels:
    app: assignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignment
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignment
        image: isuru1321/assignment:v1
