apiVersion: v1
kind: Namespace
metadata:
  name: node-app

---

# Deploy Blue Environment for Node.js
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-blue
  namespace: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
      version: blue
  template:
    metadata:
      labels:
        app: node-app
        version: blue
    spec:
      containers:
        - name: node-app
          image: node-app:latest
          ports:
            - containerPort: 5000

---

# Deploy Green Environment for Node.js
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-green
  namespace: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
      version: green
  template:
    metadata:
      labels:
        app: node-app
        version: green
    spec:
      containers:
        - name: node-app
          image: node-app:latest
          ports:
            - containerPort: 5000
